name: Lint PowerShell
on:
  push:
    paths: ["**/*.ps1"]
  workflow_dispatch:
jobs:
  ps-lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
          Invoke-ScriptAnalyzer -Path . -Recurse -Severity Warning,Error