name: Scan for Secrets
on:
  push:
  workflow_dispatch:
jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run truffleHog
        uses: trufflesecurity/trufflehog@main
        with:
          scanArguments: --regex --entropy=False ./